import PersistentLogin from "@/contexts/PresistentLogin";
import type { Metadata } from "next";
import { Abhaya_Libre, Barlow, Inter, Poppins, Rubik } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "../../components/Navbar";
import FeaturedBlogsSection from "../blog-sections/LatestBlogs";
import AuthContextProvider from "@/contexts/AuthContext";
import Providers from "@/providers/TRPC_Provider";
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const BarlowFont = Barlow({
  subsets: ["latin"],
  weight: ["100", "400", "500", "600", "700", "800", "900"],
  variable: "--font-barlow",
});
const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});
const clashDisplay = localFont({
  src: "../../../public/fonts/ClashDisplay-Variable.ttf",
  variable: "--font-clash-display",
});

const abhayaLibre = Abhaya_Libre({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-libre",
});
export const metadata: Metadata = {
  title: "Write Shit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${inter.variable} ${BarlowFont.variable} ${poppins.variable} ${clashDisplay.variable} ${abhayaLibre.variable} `}
      >
        <Providers>
          <AuthContextProvider>
            <main className="bg-[#333] min-h-screen py-4 text-white">
              <Navbar />
              <PersistentLogin>{children}</PersistentLogin>
            </main>
          </AuthContextProvider>
        </Providers>
      </body>
    </html>
  );
}
