version: '3.1'

services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=krishna
      - POSTGRES_PASSWORD=krishna
      - POSTGRES_DB=blogger
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
